server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Vendas Service Routes
        - id: vendas-service
          uri: lb://vendas
          predicates:
            - Path=/vendas/**
          filters:
            - name: CircuitBreaker
              args:
                name: vendasCircuitBreaker
                fallbackUri: forward:/fallback/vendas
            - RewritePath=/vendas/?(?<resto>.*), /$\{resto}
        
        # Taxes Service Routes
        - id: taxes-service
          uri: lb://taxesservice
          predicates:
            - Path=/taxes/**
          filters:
            - name: CircuitBreaker
              args:
                name: taxesCircuitBreaker
                fallbackUri: forward:/fallback/taxes
            - RewritePath=/taxes/?(?<resto>.*), /api/taxes/$\{resto}
        
        # History Service Routes
        - id: history-service
          uri: lb://history
          predicates:
            - Path=/history/**
          filters:
            - name: CircuitBreaker
              args:
                name: historyCircuitBreaker
                fallbackUri: forward:/fallback/history
            - RewritePath=/history/?(?<resto>.*), /$\{resto}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
